
name: Build Registerly
concurrency: Registerly

on:
  push:
    branches: [ "main" ]
    paths: [ "Registerly/**" ]
  pull_request:
    branches: [ "main" ]
    paths: [ "Registerly/**" ]
  workflow_dispatch:

env:
  PROJECT: Registerly

jobs:
  build:

    runs-on: ubuntu-latest
    
    permissions: 
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Build
      run: |
         chmod +x ./${{ env.PROJECT }}/build.sh
         cd ./${{ env.PROJECT }}/
         ./build.sh
      shell: bash
    - name: Get version
      if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch'}}
      id: get-version
      uses: kzrnm/get-net-sdk-project-versions-action@v2
      with:
        proj-path: ./${{ env.PROJECT }}/src/DeviantCoding.${{ env.PROJECT }}.csproj
    - name: Create or update release
      if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch'}}
      env:  
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ env.PROJECT }}-${{ steps.get-version.outputs.version }}
        title: ${{ env.PROJECT }} v${{ steps.get-version.outputs.version }}
        prerelease: ${{ steps.get-version.outputs.version-suffix != '' && '--prerelease' || '' }}
      run: |
        RELEASE_NAME="$(gh release list --json name,tagName,isDraft --jq '.[] | select(.tagName=="${{ env.tag }}" and .isDraft)|.name')"
        if [ -z "${RELEASE_NAME}" ]
        then
          echo "Creating new release $tag"
          echo "prerelease=$prerelease"
          gh release create "$tag" ./${{ env.PROJECT }}/src/bin/Release/*.nupkg --draft --prerelease --title "$title"
        else
          echo "Updating existing release $tag"
          gh release upload "$tag" ./${{ env.PROJECT }}/src/bin/Release/*.nupkg --clobber
        fi
      shell: bash

      
