# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build Registerly

on:
  push:
    branches: [ "main" ]
    paths: [ "Registerly/**" ]
  pull_request:
    branches: [ "main" ]
    paths: [ "Registerly/**" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Build
      run: |
         chmod +x ./Registerly/build.sh
         cd ./Registerly/
         ./build.sh
      shell: bash

